server:
  port: 8080
  servlet:
    contextPath: /demo
springdoc:
  packagesToScan: org.jp.spring    
spring:
  datasource:
    username: sa
    password: password    
my-config:
  message: This is test message for UAT
