resources:
- ../../base
#namePrefix: sit-

configMapGenerator:
- name: springboot-poc-mutu
  files:
    - application_config_override.yaml
  literals:
    - MAX_JVM_MEMORY=512
    - MIN_JVM_MEMORY=512  
      
secretGenerator:
- name: springboot-poc-mutu
  files:
    - application_secret_override.yaml

images:
- name: image-registry.openshift-image-registry.svc:5000/devteam/springboot-poc-mutu
  newName: image-registry.openshift-image-registry.svc:5000/devteam/springboot-poc-mutu
  newTag: 307964279cde50f5d4bd405b385debe0c72de1e4
